import {
  pgTable,
  text,
  timestamp,
  uuid,
  boolean,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { applications } from "./applications.js";
import { applicationUsers } from "./users.js";

export const installations = pgTable(
  "installations",
  {
    id: uuid("id").defaultRandom().primaryKey(),

    /**
     * Stable ID generated by the NNotify Flutter SDK
     * and persisted locally on the device.
     */
    installationId: uuid("installation_id").notNull(),

    applicationId: uuid("application_id")
      .notNull()
      .references(() => applications.id, {
        onDelete: "cascade",
      }),

    /**
     * Nullable because an installation can exist
     * anonymously before login.
     */
    applicationUserId: uuid("application_user_id").references(
      () => applicationUsers.id,
      {
        onDelete: "set null",
      },
    ),

    /**
     * Generic device/platform information.
     *
     * Examples:
     * android
     * ios
     * web
     */
    platform: text("platform").notNull(),

    /**
     * Optional device identifier supplied by the client.
     * NNotify does not depend on this for installation identity.
     */
    deviceId: text("device_id"),

    /**
     * Used later by FCM/APNs.
     * We can leave this null during the initial phase.
     */
    pushToken: text("push_token"),

    isActive: boolean("is_active").notNull().default(true),

    lastSeenAt: timestamp("last_seen_at", {
      withTimezone: true,
    }),

    createdAt: timestamp("created_at", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),

    updatedAt: timestamp("updated_at", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    installationUnique: uniqueIndex(
      "installations_application_installation_unique",
    ).on(table.applicationId, table.installationId),
  }),
);